version: '3.8'

services:
  web:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 7198 --reload
    volumes:
      - ./backend:/app
    ports:
      - "7198:7198"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/stock_overflow
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=harryseldon
      - POSTGRES_PASSWORD=foundation
      - POSTGRES_DB=trantor

volumes:
  postgres_data:
